server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Telecom.entity
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/backup_project?
    username: root
    password: 990603
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

#配置thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    enabled: true


#配置分页助手
pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true


