server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Telecom.entity
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/backup_project?
    username: root
    password: 990603
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

